name: My First Pipeline

on:
  push:
    branches:
      - main
env:
  ENVIRONMENT: dev
  PROJECT: Azure-Terraform

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository files
        run: ls -la

      - name: Say Hello
        run: echo "Hello Chandan! My first GitHub Pipeline is running."
        
      - name: Show GitHub Information
        run: |
          echo "Repository = ${{ github.repository }}"
          echo "Branch = ${{ github.ref }}"
          echo "Triggered by = ${{ github.actor }}"
          echo "Run Number = ${{ github.run_number }}"
      - name: Show Environment Variables
        run: |
          echo "Environment = $ENVIRONMENT"
          echo "Project = $PROJECT"
      - name: Test GitHub Secret
        run: echo "Secret is available to the pipeline"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - name: Test GitHub Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "Secret is available ✅"
          else
            echo "Secret is missing ❌"
            exit 1
          fi
